Added WatchClass command to notify users that a class is open
AWaffleInc/rubot pull request #16
Opened 2023-11-15 10:38 UTC by mr4tt

2023-11-15 23:59 UTC, mr4tt commented
email :)

2023-11-16 00:00 UTC, mr4tt commented
every time you call me a clown, i will send you an email

2023-11-16 02:10 UTC, ewang2002 requested changes

2023-11-16 02:10 UTC, ewang2002 commented on src/commands/ucsd/DeleteClass.ts
> +            formalCommandName: "DeleteClass",
```suggestion
            formalCommandName: "Delete Class",
```

2023-11-16 02:10 UTC, ewang2002 commented on src/commands/ucsd/DeleteClass.ts
> +            // Case where we might have SUBJ1 NUM1/SUBJ2 NUM2/.../SUBJn NUMn
What about the case when you have `SUBJ NUM1/NUM2/NUM3`?

2023-11-16 02:10 UTC, ewang2002 commented on src/commands/ucsd/DeleteClass.ts
> +        const searchRes = DataRegistry.COURSE_LISTING.find((x) => {
I would not use the `COURSE_LISTING` to check if a course is available. I don't maintain the course listings as often as I'd like to. Just make a request to WebReg to see if the course is there.

2023-11-16 02:10 UTC, ewang2002 commented on src/commands/ucsd/WatchClass.ts
> +            formalCommandName: "WatchClass",
```suggestion
            formalCommandName: "Watch Class",
```

2023-11-16 02:10 UTC, ewang2002 commented on src/commands/ucsd/WatchClass.ts
> +        const searchRes = DataRegistry.COURSE_LISTING.find((x) => {
Same thing as last comment

2023-11-16 02:10 UTC, ewang2002 commented on src/utilities/GeneralUtilities.ts
> +            console.log(e);
Use your logger, or remove this.

2023-11-16 02:10 UTC, ewang2002 commented on src/utilities/PostgresWatch.ts
> +                if (c) {
Shouldn't you check if `c` is not null, and then check if `c.course` is not in the map?

2023-11-16 02:10 UTC, ewang2002 commented on src/utilities/PostgresWatch.ts
> +        const seconds = 60;
Define the constant outside of this function. Use the naming convention for constants (e.g., `const SECONDS: number = 60;`)

2023-11-16 04:34 UTC, mr4tt commented
you

2023-11-16 04:34 UTC, mr4tt commented
are

2023-11-16 04:34 UTC, mr4tt commented
a

2023-11-16 04:34 UTC, mr4tt commented
big

2023-11-16 04:34 UTC, mr4tt commented
huge

2023-11-16 04:34 UTC, mr4tt commented
clown

2023-11-16 04:38 UTC, ewang2002 requested changes
ur a clown

2023-11-16 04:40 UTC, ewang2002 approved these changes

2023-11-16 04:40 UTC, merged

2023-11-17 22:52 UTC, 0AYU0 commented
attention.  a clown is approaching,